#!/bin/bash

if [ $# -ne 2 ]
then
        echo "Usage: $0 <releasename> <holdir>" >&2
        echo "  <releasename> is, for example, kananaskis-7" >&2
        echo "  <holdir> is a local HOL directory containing the docs"
        echo >&2
        echo "  Run in the topublish directory" >&2
        exit 1
fi

if [ $(basename $(pwd)) != "topublish" ]
then
    echo "Run in the topublish directory." >&2
    exit 1
fi


release=$1
shift
holdir=$1
shift

if [ -w $release-helpdocs ]
then
    echo "Deleting existing $release-helpdocs directory"
    /bin/rm -rf $release-helpdocs
fi

echo "Making directory $release-helpdocs"
mkdir $release-helpdocs

echo "Copying across help directory"
cp -R $holdir/help $release-helpdocs
cd $release-helpdocs

# first deal with the help side of things
pushd help
/bin/rm -r template HOL.Help

# correct urls in HOLindex.html
echo "Correcting URLs in HOLindex.html"
perl -p -i -e 's|file:///.*help/src-sml/htmlsigs|src-sml/htmlsigs|g;
               s|file:///.*help/theorygraph|theorygraph|g;
               s|<head>|<head><link rel="icon" href="../../images/logo.ico" type="image/vnd.microsoft.icon">|i;' HOLindex.html

# clean up src-sml a bit
cd src-sml
echo "Cleaning out source code in src-sml"
/bin/rm -f *.sml *.ML *.lex *.sig Holmakefile
/bin/rm -f index.tex index.txt Parser.grm Parser.grm.desc unCR


# correct urls in htmlsigs
echo "Correcting htmlsigs URLs and adding favicon link"
cd htmlsigs
perl -p -i -e 's|file:///.*?src/|../../../src/|g;
               s|file:///.*?help/Docfiles/|../../Docfiles/|g;
               s|(<a href=".*\.sml")|\1 type="text/plain"|gi;
               s|<head>|<head><link rel="icon" href="../../../../images/logo.ico" type="image/vnd.microsoft.icon">|i;' *.html

echo "Adding favicon link to theorygraph HTML files"
popd
pushd help/theorygraph
perl -p -i -e 's|<head>|<head><link rel="icon" href="../../../images/logo.ico" type="image/vnd.microsoft.icon">|i;' *.html
popd

# clear up help/Docfiles
pushd help/Docfiles
rm *.doc *.adoc

# now bring across src

popd
echo "Copying across src/"
cp -R $holdir/src .

echo -n "Purging copied directories "
echo -n "[HOLMK,.svn] "
find . -regex '.*HOLMK\|.*\.svn' -exec /bin/rm -rf \{\} \; -prune

echo -n "[symlink] "
find . -type l -delete

echo -n "[.u[oi],*Theory,.exe,tmp,Holmakefile] "
find . -regex '.*\.u[oi]\|.*Theory\.sml\|.*\.exe\|.*svn.*tmp\|.*~\|.*Holmakefile' -delete

echo -n "[Manual,help,examples dirs] "
find src -regex '.*Manual\|.*help\|.*examples' -execdir /bin/rm -rf \{\} \; -prune

echo "[non sml,sig]"
find src -type f \! -regex '.*\.\(sig\|\(s\|ht\)ml\)' -delete

echo "Removing some specific holdovers"
/bin/rm help/{src-sml/{DOT,README},Docfiles/{HOL.help,HTML/README},theorygraph/{README,theories.{pdf,dot,imap}}}

echo
